### ISSUE TITLE
Mech breaks the UI-Originally posted by Shrimp.tk.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#60] opened 2016-01-16 23:07 UTC
Get in a mech.

Leave the mech.

UI vanishes.

No clue why, no clue what causes it, sometimes it works fine, sometimes it doesn't. Everything seems to still be there, it's just only the mech UI visible. Relogging fixes it.

**Comment by shrimptk** [comment] 2016-01-17 01:32
Look, my post!

**Comment by BadminBen** [comment] 2016-01-17 20:13
just press F12 its not a bug

**Comment by Super3222** [comment] 2016-01-17 20:22
I'm glad this is finally getting noticed. It's been like this for months, and as Ben says it can be fixed by rotating through the HUD's with F12.

**Comment by BadminBen** [comment] 2016-01-23 10:49
the thing that happens is that your HUD doesnt update when leaving the mech sometimes. so pressing F12 will fix it every time as that's the cycle HUD button

**Closed as completed** 2016-03-05 17:11 UTC
Labels: Bug, Requires Testing
