### ISSUE TITLE
wrong SMES charging

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#570] opened 2016-03-14 08:48 UTC
### Expected Behaviour

SMES charges normally.
### Actual Behaviour

around "Server time: 2016-03-14 09:30" Electrical Maintenance SMES (I saw only that one in the round, and I was consistently scanning the wire and SMES back and forth) received 90000W in wire, displayed around 20000W incoming power, didn't charge (at 50000W input setting).
### Steps to reproduce the problem
1. Sing and 3 solars were up and wired.
2. Went to electrical maint and hooked up the SMES.
3. SMES didn't charge.

**Comment by Hydre** [comment] 2016-03-14 09:31
I guess you're talking about the solar panel ones, those have been buggy for as long as I can remember

**Comment by 00aquir** [comment] 2016-03-14 09:57
> I guess you're talking about the solar panel ones, those have been buggy for as long as I can remember

No, the solar SMESs were actually charging.. The electrical maintenance SMESs are above the chapel.

**Comment by 00aquir** [comment] 2016-03-14 10:04
Right now Tesla engine is charging the station.. Electrical maintenance wire scan and SMES now: 

600000W in wires -> 507328 W in SMES
550000W in wires -> 457328 W in SMES
450000W in wires -> 357328 W  in SMES

It seems better this time.. I don't know what happened earlier.

**Comment by ShadowDeath6** [comment] 2016-03-14 22:52
Elec maint SMES have weird wiring or something and only one gets power from wires at one time.

**Comment by 00aquir** [comment] 2016-03-14 23:25
> Elec maint SMES have weird wiring or something and only one gets power from wires at one time.

The two above mentioned events differ, the SMESs were wired the same way, just different E-source.

**Comment by Greatbigben** [comment] 2016-03-27 11:56
is this confirmed?

**Comment by 00aquir** [comment] 2016-03-27 20:19
Well no idea why, but it happened with those power sources at that time for some reason. I'll be happy if we never encounter it again.

**Comment by AsV9** [comment] 2016-05-20 22:00
Unable to reproduce, closing.

**Closed as completed by AsV9** 2016-05-20 22:00 UTC
Labels: Bug, Can't reproduce :(
