### ISSUE TITLE
White screen - dynamic lighting system

### ISSUE THREAD

**Issue by Silvaplex256** [yogstation13/yogstation-classic#88] opened 2016-01-19 16:08 UTC
Dynamic lighting is glitched for Windows vms. Fills screen with white tiles that make it impossible to see anything, Hud unaffected, will post more info when I get home.

**Comment by george99g** [comment] 2016-01-19 18:19
@TehFlaminTaco

**Comment by TehFlaminTaco** [comment] 2016-01-20 04:23
Cannot replicate, also, functionally cannot my my Coloured Lighting's fault, if it was anything, it would have existed before my coloured lighting, that, or the machine you're running it on has outdated graphics drivers that do not support multiplex blending.

Client Issue.

**Comment by TehFlaminTaco** [comment] 2016-01-20 14:26
This is a duplicate of #87

**Comment by george99g** [comment] 2016-01-20 15:25
> This is a duplicate of #87

Closing this then.

**Closed as completed by george99g** 2016-01-20 15:25 UTC
Labels: Bug, Critical, Requires Testing
