### ISSUE TITLE
theres a bug it is very annoying and game brecking

### ISSUE THREAD

**Issue by awseomenathan987** [yogstation13/yogstation-classic#215] opened 2016-02-02 21:47 UTC
I just got this websight, sorry if I fuck up.
theres a bug were theres a green eye and a loading screen with a big N in the backround.
wean I click it to open it like a air alarm or a APC or a canister it pops up a loading screen that never loads and it stays frozen forever
it has ben happening scence I first got the game and its very annoying all my friends say they don't have that problem but I do
I can get on a APc or anything with a green eye and a N in the 
backround of it and the loading screen stays there 
its just annoying and I can do anything about it please fix this bug

**Comment by george99g** [comment] 2016-02-03 11:28
A bit of punctuation would be useful.
Do you have any screenshots to show?
What operating system and hardware do you have?

**Comment by AsV9** [comment] 2016-02-05 14:10
Screenshots and hardware configuration please.

**Comment by awseomenathan987** [comment] 2016-02-11 20:38
sorry I don't have a screen shot but I am on windows 10 sorry I was so late

**Comment by awseomenathan987** [comment] 2016-02-11 20:42
don't know what you mean by hardware sorry computer noob over here

**Comment by DavidEdwards** [comment] 2016-02-12 16:09
@awseomenathan987 Please attempt to reproduce the error (make it happen again).

When it does, provide the following information:
1. A screenshot of the problem (with annotations written on it if possible)
2. Steps you took to reproduce the problem, in detail.

As it isn't entirely obvious what the problem is, I will close this issue. However, please don't be disheartened - just provide all the important information in your next issue report.

**Closed as completed by DavidEdwards** 2016-02-12 16:09 UTC
Labels: Bug
