### ISSUE TITLE
VV for Mulebots busted

### ISSUE THREAD

**Issue by SKR6DarkVoid** [yogstation13/yogstation-classic#718] opened 2016-03-28 04:10 UTC
### Expected Behaviour

Able to view the variables on the mulebots
### Actual Behaviour

As soon as I click view variables, client crashes
### Steps to reproduce the problem
1. Right click on mulebot
2. Select view variables
3. Get crashed on.

**Comment by ToGWtF** [comment] 2016-03-28 06:33
lmao it instantly crashes you

**Comment by X-TheDark** [comment] 2016-03-30 06:09
If you don't mind, is there any other information you can provide? I tried looking at Mulebot via VV on the server and it worked properly, didn't kick me out or anything.

**Comment by ToGWtF** [comment] 2016-03-31 05:56
Would instantly give you "Connection closed".

No longer happening. Was just that one single round. Cannot imagine what could have broken it

**Comment by X-TheDark** [comment] 2016-03-31 11:18
Ok, I will be closing this for now, as I cannot repeat this on the server. If there's any recurrence, feel free to reopen this. I'll see if I can test this out with moving Mulebots, etc.

**Closed as completed by X-TheDark** 2016-03-31 11:18 UTC

**Comment by Cruix** [comment] 2016-03-31 12:46
I have seen this bug before, but not with mulebots. Some games, certain object just close your connection when your try to varedit them. It is usually fixed after the server restarts. It is probably caused by some obscure networking bug where a large piece of data like the HTML for a varedit panel has some character that closes the connection it is sent over.
