### ISSUE TITLE
Admin antag HUD doesn't work with gangs

### ISSUE THREAD

**Issue by Alek2ander** [yogstation13/yogstation-classic#450] opened 2016-03-04 11:56 UTC
### Expected Behaviour

Admin antag HUD shows different colored icons for different gangs, and can distinguish bosses and normal gangsters
### Actual Behaviour

All gangsters show the same [?] unknown antag icon

**Comment by oisin100** [comment] 2016-03-13 13:43
The issue is fixed in the next server update.

**Comment by Greatbigben** [comment] 2016-03-28 08:42
This has been merged?

**Comment by oisin100** [comment] 2016-04-01 14:53
It was.

**Closed as completed by oisin100** 2016-04-01 14:53 UTC
Labels: Bug, Antag
