### ISSUE TITLE
Fire extinguishers spraying black squares.

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#126] opened 2016-01-23 03:39 UTC
http://prntscr.com/9tn5fp

Appears to be a simple icon error. will look into it.

**Comment by Hydre** [comment] 2016-01-23 11:24
Yeah sometimes the black squares even stay for some reason

**Comment by george99g** [comment] 2016-01-23 15:24
Duplicate of #71
Fixed in #73
Closing this.

**Closed as completed by george99g** 2016-01-23 15:24 UTC
