### ISSUE TITLE
Whitelist Prefs Reset

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1018] opened 2016-04-24 04:30 UTC
### Expected Behaviour

Your "Ultra" preference for AI stays Ultra.
### Actual Behaviour

I encountered this once, but I haven't tried to reproduce it, but the "Ultra" preference or whitelist preference for heads/AI resets after a round.

**Comment by X-TheDark** [comment] 2016-04-24 04:34
Duplicate of #752 
Nonetheless, don't close this. I'll take a look at this.

**Closed as completed** 2016-04-24 10:59 UTC
